### ISSUE TITLE
[Bug]: Error! Bad return status for module build on kernel: 6.16.7-arch1-1 (x86_64)

### ISSUE THREAD

**Issue by princeri** [morrownr/8812au-20210820#56]
### Checklist

- [x] I am not using this driver from inside a Virtual Machine.
- [x] I performed all of the [installation steps](/README.md#installation-steps) as written.
- [x] I have read the [FAQ](/FAQ.md) and my question is not answered there.

### Is Secure Boot enabled?

No

### uname

Linux archlinux 6.16.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 Sep 2025 17:42:36 +0000 x86_64 GNU/Linux

### lsusb

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub Bus 001 Device 002: ID 04f2:b628 Chicony Electronics Co., Ltd EasyCamera Bus 001 Device 003: ID 2357:0120 TP-Link Archer T2U PLUS [RTL8821AU] Bus 001 Device 004: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub Bus 003 Device 002: ID 0438:7900 Advanced Micro Devices, Inc. Root Hub Bus 003 Device 003: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode) Bus 003 Device 004: ID 0cf3:e500 Qualcomm Atheros Communications 

### rfkill

0: ideapad_wlan: Wireless LAN 	Soft blocked: no 	Hard blocked: no 1: ideapad_bluetooth: Bluetooth 	Soft blocked: yes 	Hard blocked: no 2: hci0: Bluetooth 	Soft blocked: yes 	Hard blocked: no 3: hci1: Bluetooth 	Soft blocked: yes 	Hard blocked: no 4: phy0: Wireless LAN 	Soft blocked: no 	Hard blocked: no

### dkms

```text
rtl8812au/5.13.6-23: added
```

### iw

```text
phy#0
	Interface wlan0
		ifindex 3
		wdev 0x1
		addr 74:fe:ce:d4:42:89
		ssid Ankur Gupta
		type managed
		channel 6 (2437 MHz), width: 20 MHz, center1: 2437 MHz
		txpower 20.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
			0	0	0	0	0	0	0	0		0
```

### git status

```text
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

### install-driver.sh

```text
: ---------------------------
: install-driver.sh v20241003
: x86_64 (kernel architecture)
: x86_64 (architecture to send to gcc)
: 2/2 (in-use/total processing units)
: 3453752 (total system memory)
: 6.16.7-arch1-1 (kernel version)
: gcc (version of gcc used to compile the kernel)
: gcc (GCC) 15.2.1 20250813
: dkms-3.2.1
: mokutil not installed (Secure Boot status unknown)
: ---------------------------

Checking for previously installed drivers...
Removing a driver that was added to dkms.
Deleting module rtl8812au/5.13.6-23 completely from the DKMS tree.
Removing 8812au.conf from /etc/modprobe.d
Removing source files from /usr/src/rtl8812au-5.13.6-23
Finished checking for and uninstalling previously installed drivers.
: ---------------------------

Starting installation.
Copying 8812au.conf to /etc/modprobe.d
The dkms installation routines are in use.
Copying source files to /usr/src/rtl8812au-5.13.6-23
Deprecated feature: CLEAN (/usr/src/rtl8812au-5.13.6-23/dkms.conf)
Creating symlink /var/lib/dkms/rtl8812au/5.13.6-23/source -> /usr/src/rtl8812au-5.13.6-23
The driver was added to dkms successfully.
: ---------------------------

Deprecated feature: CLEAN (/usr/src/rtl8812au-5.13.6-23/dkms.conf)
Sign command: /usr/lib/modules/6.16.7-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
kernelver=6.16.7-arch1-1 ./dkms-make.sh

Error! Bad return status for module build on kernel: 6.16.7-arch1-1 (x86_64)
Consult /var/lib/dkms/rtl8812au/5.13.6-23/build/make.log for more information.
An error occurred. dkms build error:  10
Please report this error.
Please copy all screen output and paste it into the problem report.
Run the following before reattempting installation.
$ sudo ./remove-driver.sh
```

### What happened?

It just failed to install the driver everytime.

This is the output of /var/lib/dkms/rtl8812au/5.13.6-23/build/make.log:

DKMS (dkms-3.2.1) make.log for rtl8812au/5.13.6-23 for kernel 6.16.7-arch1-1 (x86_64)
Sun Sep 14 01:40:57 PM IST 2025

Building module(s)
# command: kernelver=6.16.7-arch1-1 ./dkms-make.sh
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.16.7-arch1-1/build M=/var/lib/dkms/rtl8812au/5.13.6-23/build  modules
make[1]: Entering directory '/usr/lib/modules/6.16.7-arch1-1/build'
make[2]: Entering directory '/var/lib/dkms/rtl8812au/5.13.6-23/build'
  CC [M]  core/rtw_cmd.o
  CC [M]  core/rtw_security.o
core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/lib/modules/6.16.7-arch1-1/build/scripts/Makefile.build:287: core/rtw_cmd.o] Error 1
make[4]: *** Waiting for unfinished jobs....
core/rtw_security.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/lib/modules/6.16.7-arch1-1/build/scripts/Makefile.build:287: core/rtw_security.o] Error 1
make[3]: *** [/usr/lib/modules/6.16.7-arch1-1/build/Makefile:2003: .] Error 2
make[2]: *** [/usr/lib/modules/6.16.7-arch1-1/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/rtl8812au/5.13.6-23/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.16.7-arch1-1/build'
make: *** [Makefile:2516: modules] Error 2

# exit code: 2
# elapsed time: 00:00:01

**Comment by morrownr** [comment]
Hi @princeri 

This driver won't compile on kernel 6.16 because it should not need to compile on any distro using kernel 6.14 or later. Did you check to see if your adapter was working before you tried to install this driver?

A very solid rtl8812au standards compliant driver was added to the kernel with kernel 6.14. Try running the following:

$ sudo sh remove-driver.sh

After reboot, see what you have.

**Comment by cybersnow02** [comment]
Hi @morrownr and @princeri 

I made a patch so this 8812au driver will work with Kernel 6.15 and 6.16. I don't like the fact that newer kernels won't be supported anymore for this driver project. The main problem with rtw88 (see https://github.com/lwfinger/rtw88/issues/111) is that we cannot adjust the txpower anymore (higher value). So I request that @morrownr continue to update this driver until they find out a solution. Anyway, I tested my patch and it works perfectly under Debian 13 Trixie with Backport kernel 6.16.

@morrownr : can you integrate this patch to main code?

[patch_kernel_6.16.patch](https://github.com/user-attachments/files/22454137/patch_kernel_6.16.patch)

**Comment by cybersnow02** [comment]
Also, I renamed 'remove-driver.sh' to 'uninstall-driver.sh'. Take this into consideration if applying my patch.

**Comment by morrownr** [comment]
@cybersnow02 

Thanks for the information. I have no problems with users continuing to keep this driver going with API related PRs. What I would like instead on one patch is 3 PRs. One for kernel 15, one for kernel 16 and one for the change to uninstall. That will allow me to check things in a more orderly way.

> I don't like the fact that newer kernels won't be supported anymore for this driver project.

I understand but I have to make the best use of the time that I have available. Like I said, this repo can live as long as users make the API updates. 

> The main problem with rtw88 (see lwfinger/rtw88#111) is that we cannot adjust the txpower anymore (higher value).

Have you actually checked to see if txpower can actually be adjusted to a higher value with this driver? I'm not talking about the output of `iw`, I am talking about checking levels to see if the change is actually being made.

I wrote a message in lwfinger/rtw88#111 a while ago in an effort to start consolidating what we know about txpower. You are welcome to participate in this effort.

**Comment by princeri** [comment]
> Hi [@princeri](https://github.com/princeri)
> 
> This driver won't compile on kernel 6.16 because it should not need to compile on any distro using kernel 6.14 or later. Did you check to see if your adapter was working before you tried to install this driver?
> 
> A very solid rtl8812au standards compliant driver was added to the kernel with kernel 6.14. Try running the following:
> 
> $ sudo sh remove-driver.sh
> 
> After reboot, see what you have.



after uninstalling the driver it uses the 
readlink /sys/class/net/wlan0/device/driver                                                                                                                       

../../../../../../bus/usb/drivers/rtw88_8821au


this driver has problem where the packet inject doesn't works sometime....
also unable to find wifi networs when in monitor mode 

the 8812au was working absolutely fine....

**Comment by cybersnow02** [comment]
@morrownr I made incremental patches in 3 steps:
- Actual main to Kernel 6.15
- Kernel 6.15 to Kernel 6.16
- Uninstall patch (do not forget to rename file 'remove-driver.sh' to 'uninstall-driver.sh')

The 'uninstall' patch idea was taken from your other project (https://github.com/morrownr/rtl8852bu-20240418). By now, I could just try to focus on Kernel patch instead of non-urgent mods? I tried to follow your code changes between projects to match what it should be now...

[1__patch_actual_main_kernel_6.14_to_6.15.patch](https://github.com/user-attachments/files/22475960/1__patch_actual_main_kernel_6.14_to_6.15.patch)
[2__patch_kernel_6.15_to_6.16.patch](https://github.com/user-attachments/files/22475961/2__patch_kernel_6.15_to_6.16.patch)
[3__patch_uninstall.patch](https://github.com/user-attachments/files/22475962/3__patch_uninstall.patch)

**Comment by cybersnow02** [comment]
About the txpower issue for driver rtw88 (issue : https://github.com/lwfinger/rtw88/issues/111), I did some test. It is easy for me to know if txpower works or not. An easy answer would be that without your 8812au, I couldn't answer to you because I did most of the patch work sit down in a forest, way far away from the access point. Without txpower adjusted to max, I couldn't connect at all.

After kernel 616 update, I switched to new rtw88 driver but I couldn't connect anymore. So I decided to look at the issue. I discovered that iw (or iwconfig) commands doesn't show the correct txpower at all. In fact, it was fluctuating each second. Then, I tried to force it with 'iw phy1 set sar_specs 0 0:xx' (any number) without success. It remained at 20dBm all the time. So the rtw88 enforce the regulation and cannot be modified. Now, I'm thinking that Linux Kernel shouldn't force this kind of regulation to be 20dBm. If this thing doesn't break my hardware, then it shouldn't be locked at all. Doesn't the hardware just refuse the value if not supported? The hardware is the only one to authorize, not the kernel.

**Comment by morrownr** [comment]
@cybersnow02 

> So the rtw88 enforce the regulation and cannot be modified (for higher values than 20dBm).

Is -20 dBm the maximum allowable txpower setting for your country and channel you are using? If unsure, tell me your country and band/channel you are using and I will show you how to look it up.

With that said, if -20 dBm is the max allowed, then rtw88 is doing its job correctly as it should not allow you to exceed the max allowed by law. If the rtl8812au driver is allowing you to exceed the max allowed txpower, then that needs to be corrected or the driver taken down.

I'm sure that is not what you want to hear but I am pretty good at helping with cases when range needs to be extended... legally.

**Comment by princeri** [comment]
> Hi [@morrownr](https://github.com/morrownr) and [@princeri](https://github.com/princeri)
> 
> I made a patch so this 8812au driver will work with Kernel 6.15 and 6.16. I don't like the fact that newer kernels won't be supported anymore for this driver project. The main problem with rtw88 (see [lwfinger/rtw88#111](https://github.com/lwfinger/rtw88/issues/111)) is that we cannot adjust the txpower anymore (higher value). So I request that [@morrownr](https://github.com/morrownr) continue to update this driver until they find out a solution. Anyway, I tested my patch and it works perfectly under Debian 13 Trixie with Backport kernel 6.16.
> 
> [@morrownr](https://github.com/morrownr) : can you integrate this patch to main code?
> 
> [patch_kernel_6.16.patch](https://github.com/user-attachments/files/22454137/patch_kernel_6.16.patch)

Can you please share me your patched version 8812au driver.

**Comment by morrownr** [comment]
@cybersnow02 

If you are interested, I can give you admin rights to this repo so that you can take over maintenance of this repo. This might be the best solution. I would ask you to consider your changes carefully as I have numerous Realtek WiFi 5 vendor drivers up here and it is best if they work in a consistent manner. An example of what I am talking about is the change from `remove` to `uninstall`. I understand the desire as I am the one that made that change starting with the Realtek WiFi 6 drivers... however I do not think it is a good change for WiFi 5 at this point as keeping things consistent would require the change in all drivers and in the docs and in the mind of all current users... and this is a repo that gets a lot of hits per day. I will leave things alone as far as API changes go as long as you don't break things but other things that can lead to a lot of message traffic is something to avoid. 

What do you think?

**Comment by cybersnow02** [comment]
@morrownr 

I just want to contribute by sending patches if able to fix it with my current skills :) I do not want to take over maintenance of this repo.

I have a question for you. You said : "I understand but I have to make the best use of the time that I have available". Then, you seem to abandon this project because you prefer the RTW88 alternative since 8812au in now included with the kernel. But, by looking of the work you do with RTL8852BU, you could easily backports the same kind of fixes in 10 minutes like I did, since they are compatible. When the 8852BU will be included in the future kernel, are you going to stop maintaining it as well? I mean, for now, the kernel changes aren't too complicated to justify not supporting it anymore. What I'm doing right now is trying to help you with patches to save you some time. You could then just approve patches from users and add them to the repo?

**Comment by cybersnow02** [comment]
@princeri 
To apply patches, you can follow this guide:
https://www.cyberciti.biz/faq/appy-patch-file-using-patch-command/

**Comment by cybersnow02** [comment]
By the way, I just realized that I made the patches according to the following commit in February 21, 2025. So before applying my patches, download the right commit main code: https://github.com/morrownr/8812au-20210820/commit/dabcb74da670a12ca74125588bc89aa8ad086c13

At this stage, it already included the Kernel 6.14 patches. thanks

**Comment by morrownr** [comment]
> I just realized that I made the patches according to the following commit in February 21, 2025. So before applying my patches

I think you are making this harder than it needs to be. If you want me to merged the patches, make PR requests. That will speed things up on my end and eliminate some potential problems. Remember to git pull so that your repo is at the same level before doing anything.

So that there is no confusion:

> I have a question for you. You said : "I understand but I have to make the best use of the time that I have available". Then, you seem to abandon this project because you prefer the RTW88 alternative since 8812au in now included with the kernel. But, by looking of the work you do with RTL8852BU, you could easily backports the same kind of fixes in 10 minutes like I did, since they are compatible. When the 8852BU will be included in the future kernel, are you going to stop maintaining it as well?

Absolutely I am going to stop maintaining the rtl8852bu repo. In fact, the new rtw89 driver for the rtl8952bu chip just went into kernel 6.17. I will probably stop maintaining it and rtl8852cu with the kernel that goes into Ubuntu 26.04. I am aware of user needs and try to accommodate a transition period. I also leave the repos available and accepted PRs tfrom users that want the drivers available for future kernels. The alternative is that I make two clicks and remove the repos from public viability.

What you may not understand is that the Realtek USB vendor drivers are bad in many ways. They are not designed for end users. They are designed for embedded purposes. The Linux development cycle makes it where out-of-kernel , non-standards compliant drivers are very problematic. I have put in many hours over the last several years trying to make the Realtek vendor drivers as user friendly as possible but there are basic limits. The new drivers that we are making are Linux standards compliant drivers (mac80211) and are handled the way Linux drivers should be handled... in-kernel with coordination done in linux-wireless. I CANNOT over emphasize how much better the new drivers are. You have a very specific case for the reason you want this driver to be maintained. I would much prefer that you move to rtw88 and I will be glad to work with you to find a solution to your problem.

**Comment by cybersnow02** [comment]
I used another antenna and my TX is working fine now (antenna was broken) and this driver respect the regulation. thanks.

**Comment by morrownr** [comment]
@princeri 

I am willing to work with you if you decide to start using the new rtw88 driver. I think you will find the new driver to be quite good.

**Comment by walmis** [comment]
I've been experiencing some issues with **rtw88 on Kernel 6.16** (Archer T4UH Wi-Fi dongle):

* **5 GHz Wi-Fi instability:** Frequent disconnections; `dmesg` shows repeated `CLASS3_FRAME_FROM_NONASSOC_STA` messages.
* **macvtap broken:** Guests using libvirt/QEMU can no longer access the local network directly.

Just my perspective as a user - my previous **8812au setup was stable for several years** without these issues.
Thanks to these patches, I can roll back to 8812au and continue using my existing hardware.

**Comment by morrownr** [comment]
Hi @walmis 

> I've been experiencing some issues with rtw88 on Kernel 6.16...

Thanks for the report. I need you to report this to the downstream repo where the work is done on rtw88:

https://github.com/lwfinger/rtw88

Make sure the title of the issue says the chipset of your adapter (rtl8812au)

> Just my perspective as a user - my previous 8812au setup was stable for several years without these issues.

I understand. I have put many hours in over the years trying to keep this driver in as good of shape as I could. I am only too aware that it has many shortcomings. With that said, I also realize that it has performed very well for many people for a long time and you appear to be in that category. I can write a long list of reasons why the community needs the new rtw88 and rtw89 USB WiFi drivers but if something is not working then the list doesn't matter... I get it.

I am actually setup to do some testing if I can get you to file your bug over at the rtw88 repo. I'll try to help confirm and see if we can fix it.

One thing I am going to be asking you is if you run your adapter in USB3 mode. With the driver in this repo, setting USB3 requires changing a module parameter whereas changing to USB3 mode is automatic with rtw88.

I hope to see you in the rtw88 repo as shown above.
